apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 740186512853.dkr.ecr.us-east-1.amazonaws.com/gitops-frontend:0dcc8db121d8c3c2c2f493b7b98213370df72d1b
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: http://54.84.239.147:30001
