apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 740186512853.dkr.ecr.us-east-1.amazonaws.com/gitops-frontend:29d9f0bf5fd1af74db369ca0aaa6b8d8fd3ebbe5
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: http://54.84.239.147:30001
