apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 740186512853.dkr.ecr.us-east-1.amazonaws.com/gitops-frontend:df18c9e71d3b22650c87f0493f4a9c1481f62cd8
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: http://54.84.239.147:30001
